### ISSUE TITLE
Vocabulary size code explanation and occasionally shape error

### ISSUE THREAD

**Issue by Vimos** [huggingface/pytorch-openai-transformer-lm#38]
From the model definition, `vocab` is used to define the size of embedding.
    
       vocab = n_vocab + n_special + n_ctx

I am guessing that the `n_ctx` here is used for the position embedding, but still not clear.

In my case, I sometimes run into the following shape error if `n_ctx` is very large.

```
Traceback (most recent call last):
  File "/home/vimos/git/QA/pytorch-openai-transformer-lm/train.py", line 413, in <module>
    load_openai_pretrained_model(dh_model.transformer, n_ctx=n_ctx, n_special=n_special)
  File "/home/vimos/git/QA/pytorch-openai-transformer-lm/model_pytorch.py", line 402, in load_openai_pretrained_model
    assert model.embed.weight.shape == init_params[0].shape
AssertionError: (torch.Size([41140, 768]), (40993, 768))
```

Can anybody explain the code?  Should I restrict `n_ctx` to a value?
Thanks!

**Comment by Vimos** [comment]
Oh, I believe that's why `n_ctx` is used to define the network structure and dynamic length is not working.

Thank you for the explanation!
